version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci --legacy-peer-deps
      - echo Logging in to Amazon ECR...

  pre_build:
    commands:
      - ECR_BASE_URL=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - IMAGE_URI=${ECR_BASE_URL}/${ECR_IMAGE_NAME}:${NEW_TAG}
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_BASE_URL}

  build:
    commands:
      - echo Building Docker image...
      - docker build -t ${ECR_IMAGE_NAME}:${NEW_TAG} .
      - docker tag ${ECR_IMAGE_NAME}:${NEW_TAG} ${IMAGE_URI}

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push ${IMAGE_URI}
